### ISSUE TITLE
请问能否增加上传到s3的钩子？

### ISSUE THREAD

**Issue by PonyMaLoveJackMa** [sapicd/sapic#14]
RT，希望大佬能加上对S3的支持。

**Comment by PonyMaLoveJackMa** [comment]
还有个想法，能不能在用户上传后直接把图片压缩为avif/webp？
然后返回webp的图片地址。
https://blog.rexskz.info/use-openresty-to-optimize-image-size-with-avif-and-webp.html

**Comment by staugur** [comment]
回复这两个问题，都可以用扩展实现。


1. 加一个存储后端s3，参考up2cos，本质都是上传到对象存储。


2. 压缩webp格式可以用扩展实现，上传的文件内容经过扩展处理，可以压缩、添加水印诸如此类。
如果，你只是想要访问时为webp格式，那可以选择存储后端，云服务的对象存储都可以转换，图片URL加上一些指令即可。


如果你会python的话，可以尝试自己实现（我来提供详细沟通说明），如果不会，我把它列入计划，但最近在换工作，时间上需要延后。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："PonyMaLoveJackMa ***@***.***&gt;;
发送时间：2021年7月10日(星期六) 下午3:44
收件人："sapicd/sapic" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [sapicd/sapic] 请问能否增加上传到s3的钩子？ (#14)
-----------------------------------

 

 
还有个想法，能不能在用户上传后直接把图片压缩为avif/webp？
 然后返回webp的图片地址。
 https://blog.rexskz.info/use-openresty-to-optimize-image-size-with-avif-and-webp.html

**Comment by staugur** [comment]
目前增加了上传到s3的钩子，可以试用看看。

后台-钩子扩展-安装第三方包，up2s3安装后，添加第三方钩子启用。
