### ISSUE TITLE
请问Docker images使用的是多少端口呢,不需要开端口吗 我run的时候使用-P(大写的P)run 并没有随机给端口

### ISSUE THREAD

**Issue by mhpsy** [sapicd/sapic#15]
我不是很清楚怎么回事,我不是很会用dockers-compose,
![image](https://user-images.githubusercontent.com/82896623/130583398-ed2e7ada-7ddc-4d7f-8dc9-19ebe08cb725.png)

**Comment by staugur** [comment]
端口9514，dockerfile暴露了，docker-compose也发布了，up运行后，正常本地9514端口会监听，有sapic进程

**Comment by staugur** [comment]
如果没问题，稍后将关闭Issue

**Comment by staugur** [comment]
不好意思，我看了下Dockerfile，发现没有Expose，应该是没它，所以Run时docker无法确定端口，故无映射。

目前可以使用host模式，或指定映射9514端口（注意目前版本默认监听主机127.0.0.1，此方式需配置监听0.0.0.0）。

dev分支的新提交已增加Expose~
