### ISSUE TITLE
图片上传覆盖的问题

### ISSUE THREAD

**Issue by IU520CF** [sapicd/sapic#18]
同名文件后面上传的会覆盖之前上传的图片(本人才疏学浅，暂时只能想到，写个条件判断上传图片已存在文件名称加后缀拼接，再次判断是否还是名称重复，不重复再存入。)

**Comment by staugur** [comment]
登录用户上传的图片总是位于自己的用户名下，所以无论怎么修改都不影响别人， 但注意，如果使用规则中的默认选项（无子目录且使用文件原名），以前上传的 图片很有可能会被后上传的图片覆盖，而且保存图片的钩子可能不支持覆盖（目 前内置钩子只有GitHub、Gitee不会覆盖，上传提示失败）。

> 引用文档来源：[用户自定义图片上传前缀和文件名](https://sapic.rtfd.vip/zh_CN/latest/usage.html#id6)

----
sapic只负责接收图片和配置，保存图片由上传钩子（依据配置）完成，默认由up2local保存到本地，当然是可以判断是否存在，但更多的上传钩子，比如up2github、up2gitee、up2upyun，这一行为**不统一**，加之可以自由设定前缀和命名，是否覆盖就保持默认（上传钩子自行决定），但不能宣称百分百覆盖或不覆盖。
