### ISSUE TITLE
Chrome图片无法显示的时候返回200导致透明无法选中删除

### ISSUE THREAD

**Issue by elmagnificogi** [sapicd/sapic#19]
图片无法显示的时候无法删除

比如我把一个xx.rar文件改成了xx.rar.jpg文件，临时存储到了图床上

然后我想删除他的时候，发现这个文件由于不能预览就看不到，就无法删除了
（所以如果这个图片无法预览给他一个默认的x图片预览？然后可以删除）

除非我进数据库里找他、删他

**Comment by staugur** [comment]
哦？晚点我测试下

**Comment by staugur** [comment]
图片不正常时也有一个裂开的方形占位，仍然可以点击显示弹窗，功能按钮可用。
不过我记得早前有一版代码是懒加载，会不显示，看看代码版本，及试试更新最新。

**Comment by elmagnificogi** [comment]
![image](https://user-images.githubusercontent.com/10891822/173113029-650c504f-90dd-4e5b-b90b-6a62e832fa46.png)
你是一页10个图吧？ 我这里明显不够

**Comment by staugur** [comment]
![202206110437538388.png](https://static.saintic.com/picbed/service/2022/06/11/202206110437538388.png)

1.13.4是新的，不过我是上传到又拍云。
麻烦提供下信息：上传后端（本地、又拍云、其他），你的浏览器及版本，是否有浏览器扩展作用在此图床站？

**Comment by elmagnificogi** [comment]
应该是我的问题了，我的chrome不显示这个图，但是我用firefox打开，总算是看到了破损的图片
chrome F12 会有以下提示
> Failed to load resource: the server responded with a status of 404 (NOT FOUND)
>xxxxx.xxxx.xxxx/control/undefined 404 (NOT FOUND)

**Comment by elmagnificogi** [comment]
我的chrome怎么都不显示这个破损的图片，我去掉插件，开隐身模式也不行，很奇怪。
你是用chrome还是什么？

**Comment by elmagnificogi** [comment]
对比了一下2个浏览器
我在chrome里，请求这个图片，它返回的是200，但是在firfox里返回的是304，304就会显示破损图片了，而200这个返回的是个透明图片，根本看不到

**Comment by staugur** [comment]
chrome确实是，不过不是不显示，而是破损时显示的是小白点一样的，根本看不清楚！

我跟进下，加入TODO，考虑加载失败出一个默认图。

**Comment by staugur** [comment]
显示图片时增加个 `alt` 就行了。。。

**Comment by elmagnificogi** [comment]
啥意思 按alt？

**Comment by elmagnificogi** [comment]
ok 更新到最新 有了
