### ISSUE TITLE
请问并发情况怎么样？谢谢

### ISSUE THREAD

**Issue by kingmo888** [sapicd/sapic#25]
如题，
之前一直在寻找py有关图床的实现版本，功能上类似于可以自建FTP或上传到私有云上，或上传到多点，然后通过返回伪静态地址，301到源地址（实际是HIDOVE图床功能）。

现在找到sapic图床，因为基于flask，对并发情况不是很了解，由于以前用django搞过效率一般，所以想在二开前咨询一下。

或者若flask并发不足的话，fastapi有没有可能？

**Comment by staugur** [comment]
1. 你需要的功能理论上sapic可以实现，但现在限制着。
2. 同为传统python web框架，比django并发强，但是不会强太多。
3. 如果摒除所有插件式，可以改为sanic

**Comment by saintak** [comment]
> 1. 你需要的功能理论上sapic可以实现，但现在限制着。
> 2. 同为传统python web框架，比django并发强，但是不会强太多。
> 3. 如果摒除所有插件式，可以改为sanic

我不太了解图床这个产品的模式，如果直接给出第三方（比如腾讯云cos）的地址，是不是就可以把流量引走，这样平台的稳定性和并发能力也不会影响图片的展示？

**Comment by staugur** [comment]
是的，图床只是方便图片集中查看管理，实际使用中引用的图片真实地址，如果是本地那就是图床本身（上个nginx做静态接收那也不用操心），如果是其他云，那用的时候就跟图床没关系。
