### ISSUE TITLE
[Feature]希望作者加一个backblaze B2云存储的钩子

### ISSUE THREAD

**Issue by brandeo** [sapicd/sapic#33]
**描述**
如图增加一个云存储
![图片](https://user-images.githubusercontent.com/28433305/223218894-1bfe0237-7933-44a1-b16e-55aa4db9a6a0.png)

**Comment by Vonfruit** [comment]
[图片](https://user-images.githubusercontent.com/28433305/223218894-1bfe0237-7933-44a1-b16e-55aa4db9a6a0.png)

**Comment by staugur** [comment]
可以参考API自行使用Python实现，提交到[awesome](https://github.com/sapicd/awesome)。

如无开发技能，请提供此云存储的网站地址和调试账号密码。

**Comment by staugur** [comment]
可以试用下 https://github.com/sapicd/up2b2
尚未发布，用开发版本安装试试看
