### ISSUE TITLE
镜像回源功能-<用户访问您的域名图片时，图片自动上传到我们的图床>

### ISSUE THREAD

**Issue by wwwwc** [sapicd/sapic#34]
镜像回源功能用于将您的网站下的图片自动同步到我们的图床上，您可以像使用CDN一样来使用它。您无需更改任何服务器设置，就像CDN一样，只需要将您的域名指向我们提供的CNAME记录即可。

如果您的图片位于您自己的服务器上，只需要在下方服务器地址处填写您的服务器IP地址，然后将您的域名CNAME记录修改至我们提供的CNAME记录值即可。

当用户访问您的域名时，我们会自动将该域名下的图片上传到我们的图床，您可以在上传历史看到图片上传记录。

图片上传完成后，当您再次打开您域名下的图片时，会发现地址已经变成了图床地址，不再消耗您服务器的流量或者对象存储的流量。

对于非图片请求，我们会直接反代至您的网站，不会影响您原先的内容展示。

《参考》目标功能网站：https://www.superbed.cn/admin#item=12

**Comment by staugur** [comment]
之前看反了，看这个功能，实现不了类似的~

**Comment by wwwwc** [comment]
有没有别的思路，能加速！
不需要搬家之类的！

**Comment by staugur** [comment]
后端用腾讯、阿里云、又拍云等，他们可以开启CDN
