### ISSUE TITLE
无法正常使用docker-compose启动

### ISSUE THREAD

**Issue by Hamakaze1s** [sapicd/sapic#35]
用docker-compose up -d启动后，webapp似乎一直在重启
![image](https://github.com/sapicd/sapic/assets/50857024/49ecc369-9ce9-4fc6-a3af-c3b0cd3a8d24)

**Comment by staugur** [comment]
最新版本吗？
docker logs picbed-webapp-1 看下日志

**Comment by Hamakaze1s** [comment]
![image](https://github.com/sapicd/sapic/assets/50857024/866595a2-04ef-4c26-a8c8-11ab89dae35f)
似乎是redis的问题？

**Comment by staugur** [comment]
另外，新版本名称都是sapic前缀，你的代码可能不是最新的

**Comment by Hamakaze1s** [comment]
谢谢，似乎就是版本太老的问题。
我参考的是[这个教程](https://sapic.rtfd.vip/zh_CN/1.7.0/docker.html#id3)，里面描述的仍然是从staugur/picbed克隆
重新从sapic克隆后似乎一切正常了
